# This is a basic workflow to help you get started with Actions

name: Testing and Linting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing the Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pylint
          pip install pylint-exit
      - name: Testing using pytest
        run: |
          cd src/;python -m pytest
      - name: Linting using pylint
        run: |
          pylint src/HBDU/__init__.py || pylint-exit $?
          pylint src/HBDU/views.py || pylint-exit $?
          pylint src/HBDU/models.py || pylint-exit $?
